services:
  - type: web
    name: backECO
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npx @nestjs/cli build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
    healthCheckPath: /health
